<div class="mx-auto max-w-2xl space-y-8 py-4">
  <div>
    <h1 class="text-2xl font-bold text-zinc-100">Best Practices</h1>
    <p class="mt-2 text-sm text-zinc-400">Tips for getting the best results when saving your generated PDFs.</p>
  </div>

  <div class="rounded-xl border border-zinc-700 bg-zinc-900 p-6 space-y-6 text-sm text-zinc-400">
    <div>
      <h2 class="mb-2 text-base font-semibold text-zinc-200">Disable "Headers and footers"</h2>
      <p>
        Before saving, make sure <span class="font-medium text-zinc-300">Headers and footers</span>
        is unchecked in the print dialog. The generated PDF already includes all the information it
        needs — the browser's default headers and footers (page title, URL, date, page numbers) are
        not needed and will overlap with the document layout.
      </p>
      <ol class="mt-3 list-decimal space-y-1 pl-5">
        <li>In the print dialog, click <span class="font-medium text-zinc-300">More settings</span>.</li>
        <li>Uncheck <span class="font-medium text-zinc-300">Headers and footers</span>.</li>
        <li>Save as PDF as usual.</li>
      </ol>
    </div>

    <div>
      <h2 class="mb-2 text-base font-semibold text-zinc-200">Preview vs actual PDF</h2>
      <p>
        The in-app preview is an approximation. The actual PDF is generated by your browser's
        print engine, which handles page breaks more accurately — for example, it can split a
        long paragraph across two pages, while the preview cannot.
      </p>
      <p class="mt-2">
        Always use <span class="font-medium text-zinc-300">Save as PDF</span> to check the
        final result. The preview is useful for a quick overview, but the printed output is
        the source of truth.
      </p>
    </div>
  </div>
</div>
